# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-18 18:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newpmpro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869537))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869592))),
                ('isDeleted', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 870378), verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 18, 18, 1, 56, 870442), verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('mobileNumber', models.CharField(max_length=25)),
                ('isSubscribed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', newpmpro.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PartnerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869537))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869592))),
                ('isDeleted', models.BooleanField(default=False)),
                ('instituteName', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869537))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869592))),
                ('isDeleted', models.BooleanField(default=False)),
                ('projectTitle', models.CharField(max_length=25)),
                ('projectCategory', models.CharField(max_length=25)),
                ('projectType', models.CharField(max_length=25)),
                ('projectLanguage', models.CharField(max_length=25)),
                ('ieePaper', models.BooleanField(default=False)),
                ('projectAbstract', models.TextField()),
                ('projectFrameWork', models.CharField(max_length=25)),
                ('isActive', models.BooleanField(default=True)),
                ('projectStatus', models.CharField(default=b'PROJECT UPLOADED', max_length=25)),
                ('projectOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpmpro.PartnerDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectIdeas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869537))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869592))),
                ('isDeleted', models.BooleanField(default=False)),
                ('projectIdeaStatus', models.CharField(default=b'IDEA RECEIVED', max_length=25)),
                ('projectInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpmpro.ProjectData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869537))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 7, 18, 18, 1, 56, 869592))),
                ('isDeleted', models.BooleanField(default=False)),
                ('sources', models.CharField(max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
