# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-20 17:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpmpro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126609))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126695))),
                ('isDeleted', models.BooleanField(default=False)),
                ('projectRequestStatus', models.CharField(default=b'REQUESTED', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='partnerdetails',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126609)),
        ),
        migrations.AlterField(
            model_name='partnerdetails',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126695)),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126609)),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 127991), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 20, 17, 14, 26, 128100), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126695)),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126609)),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126695)),
        ),
        migrations.AlterField(
            model_name='projectideas',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126609)),
        ),
        migrations.AlterField(
            model_name='projectideas',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126695)),
        ),
        migrations.AlterField(
            model_name='usersources',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126609)),
        ),
        migrations.AlterField(
            model_name='usersources',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 17, 14, 26, 126695)),
        ),
        migrations.AddField(
            model_name='projectrequests',
            name='projectInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpmpro.ProjectData'),
        ),
        migrations.AddField(
            model_name='projectrequests',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
