# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-20 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpmpro', '0002_auto_20170720_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerdetails',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 162939)),
        ),
        migrations.AlterField(
            model_name='partnerdetails',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 163041)),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 162939)),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 164458), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 20, 15, 57, 50, 164589), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 163041)),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 162939)),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 163041)),
        ),
        migrations.AlterField(
            model_name='projectideas',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 162939)),
        ),
        migrations.AlterField(
            model_name='projectideas',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 163041)),
        ),
        migrations.AlterField(
            model_name='projectrequests',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 162939)),
        ),
        migrations.AlterField(
            model_name='projectrequests',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 163041)),
        ),
        migrations.AlterField(
            model_name='usersources',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 162939)),
        ),
        migrations.AlterField(
            model_name='usersources',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 20, 15, 57, 50, 163041)),
        ),
    ]
