# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-21 17:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpmpro', '0003_auto_20170820_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856))),
                ('isDeleted', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856))),
                ('isDeleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802))),
                ('modifiedAt', models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856))),
                ('isDeleted', models.BooleanField(default=False)),
                ('tagName', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='partnerdetails',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802)),
        ),
        migrations.AlterField(
            model_name='partnerdetails',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856)),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802)),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 145719), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 8, 21, 17, 39, 30, 145794), verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='pmuser',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856)),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802)),
        ),
        migrations.AlterField(
            model_name='projectdata',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856)),
        ),
        migrations.AlterField(
            model_name='projectideas',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802)),
        ),
        migrations.AlterField(
            model_name='projectideas',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856)),
        ),
        migrations.AlterField(
            model_name='projectrequests',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802)),
        ),
        migrations.AlterField(
            model_name='projectrequests',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856)),
        ),
        migrations.AlterField(
            model_name='usersources',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144802)),
        ),
        migrations.AlterField(
            model_name='usersources',
            name='modifiedAt',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 21, 17, 39, 30, 144856)),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpmpro.Categories'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpmpro.Tags'),
        ),
    ]
